version: '3'

services:

  ssdb:
    build:
      dockerfile: ./Dockerfile
    # container_name: ssdb
    restart: always
    volumes:
      - ./data:/ssdb/var
      - ./ssdb.conf:/ssdb/ssdb.conf:ro
    ports:
      - 8890:8890
    networks:
      - ssdb-net

networks:
  ssdb-net:
    driver: bridge